server:
  port: 9090
  servlet:
    context-path: /yingx
    jsp:
      init-parameters:
        development: true
spring:
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/yingx
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.cn.entity
  mapper-locations: classpath:com/cn/mapper/*Mapper.xml